- README.md
- add dependencies badge
- add devDependencies badge
> docs(readme): add david-dm badges

- README.md
> docs(readme): add contributions welcome badge

- package.json
- 'files' is an array of file patterns that describes the entries to be included when publish package
> build(npm): add 'files' field in package.json

- README.md
replace footer by a link to the license
> docs(readme): remove FOSSA badge and footer

- package.json
- add 'docs' to package.json#files
Closes #19
> build(npm): publish docs folder

- __tests__/testHandler.js
- src/testHandler.js
> feat(testHandler): throw when not enough runned io

- .circleci/config.yml
- README.md
- package-lock.json
- package.json
> ci: add codecov support

- codecov.yml
Add codecov.yml config file : 
```yml
comment: false
```
> ci: add codecov yml config file

- README.md
> docs(readme): fix nsp badge

- .circleci/config.yml
> ci(lockfile): improve install job un circleci config

- package-lock.json
- package.json
* chore(package): update lockfile
> chore(package): update jest to version 23.0.0-alpha.0 🚀

- src/internal/BypassHandlerError.js
> fix(internal): BypassHandlerError now have a .stack property

- .circleci/config.yml
- README.md
- package-lock.json
- package.json
- remove 'bump', 'create-changelog' and 'version' npm script
- install semantic-release
- install @semantic-release/git
- install @semantic-release/changelog
- configure semantic-release (in package.json)
- add circleci 'release' job
- add badge in README.md
Closes #68
> ci: install and configure semantic-release

- README.md
Improve some wording, correct some mistakes, add a `function` a bunch of time. Next step is the famed @lenemson review.
Closes #92
> docs(readme): improve wordings in the readme

- .circleci/config.yml
> ci: install npm@latest and use npm ci

- .markdownlintrc
- CONTRIBUTING.md
- README.md
- package-lock.json
- package.json
- install markdownlint
- use markdownlint in npm "lint" script
- create custom configuration .markdownlintrc file
Closes #97
> ci(lint): install and configure markdownlint

- .circleci/config.yml
in circleci install job
Closes #103
> ci: add fallback to npm ci

- __tests__/internal/BypassHandlerError.js
- codecov.yml
- package.json
- improve BypassHandlerError tests
- add jest coverage thresholds
- update codecov.yml thresholds to be more strict on coverage regressions
- change test:all script to run test:coverage instead of test
Closes #72
> test: improvements to reach 100% code coverage

- README.md
- __bundle_tests__/api.js
- __bundle_tests__/example-readme-errors.js
- __tests__/catchError.js
- src/catchError.js
- src/index.js
- write documentation
- refactor `src/index.js`
- write implementation
- write unit tests
- improve `__bundle_tests__/example-readme-errors.js`
Closes #47
> feat: add catchError

- package-lock.json
- package.json
> ci(semantic-release): exec test:all script in verifyConditions

- README.md
"Deal with errors" -> "Dealing with errors"
> docs(readme): rephrasing title

- README.md
> docs(readme): fix missing require in examples

- README.md
- __tests__/handler.js
- __tests__/io.js
- src/handler.js
- src/io.js
.run method is available in both unapplied io and handler
Closes #120
> feat: make .run method available everytime

- package-lock.json
- package.json
> chore(package): update markdownlint-cli to version 0.8.1 🚀

- README.md
> docs(readme): add gitter badge

- __tests__/index.js
> test(api): add missing catchError api test

- __bundle_tests__/api.js
replace hardcoded api keys by an Object.keys of imported handle-io from src
Closes #126
> test(api): improve bundle api test

- README.md
- __bundle_tests__/example-readme-errors.js
- __tests__/simulateThrow.js
- __tests__/testHandler.js
- src/index.js
- src/internal/SimulatedThrow.js
- src/simulateThrow.js
- src/testHandler.js
- implementation
- unit tests
- documentation
- readme example test (bundle tests)
Closes #117
> feat: add simulateThrow

- README.md
> docs(readme): add "Use with Redux" part

- .dont-break.json
- package-lock.json
- package.json
test(redux-fun): configure dont-break and add test:dont-break script
> ci(release): configure dont-crack semantic-release plugin

- .npmrc
save-prefix is useful to greenkeeer auto updates
> chore(npmrc): add save=false and save-prefix='='

- package.json
> chore(package): update semantic-release to version 15.4.1

- .circleci/config.yml
- package-lock.json
in order to avoid greenkeeper-lockfile issues
> ci(config): simplify circleci workflow

- package-lock.json
- package.json
> chore(package): update sinon to version 6.0.0

- package-lock.json
- package.json
> chore(package): update rollup to version 0.60.7

- package-lock.json
- package.json
> chore(package): update semantic-release to version 15.5.4

- package-lock.json
- package.json
> chore(package): update commitizen to version 2.10.1

- package-lock.json
- package.json
> chore(package): update eslint-plugin-jest to version 21.17.0
